const icon = document.querySelector('.disclosure-icon');
const content = document.querySelector('.disclosure-content');

icon.addEventListener('click', () => {
  content.classList.toggle('is-hidden');
  icon.querySelector('i').classList.toggle('rotate');
});

function onInputChange(event) {
  const value = event.target.value;
  buildList(value);
}

const input = document.getElementById("search-input");
input.addEventListener("input", onInputChange);

const clearButton = document.getElementById("clear-button");
clearButton.addEventListener("click", event => {
  input.value = '';
  buildList();
});

function buildList(search = null) {
  const strings = filteredHalaprops(search);
  const root = document.getElementById('list-root');
  root.innerHTML = strings.map(str => {
    return `<a class="panel-block ml-4">${str}</a>`
  }).join('\n');
}
buildList()

function filteredHalaprops(search) {
  const halaprops = [
    "Put a stakeholder in the ground",
    "You sure cleaned my butt",
    "Coming along with fits and spurts",
    "Seen a few of those in my heyday",
    "Mention that idea to the client...just to tread the water",
    "The ball of wax is in your court",
    "A slap behind the ears",
    "We're driving the show",
    "We've bridged that hurdle",
    "That's another bag of worms",
    "They pulled the rug out from over our eyes",
    "Out the kazoo",
    "Lets tee-up and kick off the next topic",
    "Not his bag of tea",
    "Knashing at the bit",
    "We tweaked their interest, now we're being inundighted (sic) with requests",
    "Burning both candles at the end",
    "You're talking to the choir",
    "We're at the forefront of a crossroads",
    "I lowered the boom and rose a red flag",
    "You're trying to beat it with a dead horse",
    "I'm just talking from the hip",
    "That knocked me off my socks",
    "He's the dark horse of the family",
    "You were snoring like a log ",
    "We'll cross that bridge when we know it's been blown up",
    "We created this beast, now we have to run with it",
    "We need to rope in some partners to help tow the line",
    "We need to flush out that idea",
    "That's the end-all, beat-all",
    "After you make an omelette, you can't put Humpty Dumpty back together again",
    "You hit that nose right on the head",
    "Dead as a doorknob",
    "You can lead a horse to water, but if he's fucked there's nothing you can do",
    "Making money hand over foot",
    "Let's jump to the chase",
    "Make sure we have our ducks in a row before we run down that path",
    "It doesn't have to be the drop-dead end-all",
    "I hope I didn't step on a nerve",
    "The carrot at the end of the tunnel",
    "We're cutting hairs",
    "The red herrings are flying hot and heavy",
    "We need a straw pole on whether....",
    "That's a whole other kettle of wax",
    "Put my head to the grindstone",
    "It was a three-pronged ball drop",
    "He makes my blood curl",
    "We need to hold his teeth to the fire",
    "He stole my fire",
    "That idea has been bambi-ed about recently",
    "Now she's happy as a lamb",
    "He doesn't have enough horse-power to start a fire",
    "I got the shitty end of the stick",
    "We need a rehaul of the whole process",
    "That's a sweet penny ",
    "We can get a leg in the door",
    "He's got too many buns in the oven",
    "We wouldn't want to pin our hats on that",
    "That smacks in the face of....",
    "It's time to lay your dick on the table",
    "We're the cookie on the table. People have to shoot at us now.",
    "We're passing the stapler",
    "We can't change horses once we proceed",
    "Dressed to the teeth",
    "It's a shut and dry case",
    "Now they've been tripped off",
    "Stirring the bushes",
    "Came to fruitation",
    "It's coming down the pipe",
    "Mixing and matching apples",
    "That's just water under the carpet",
    "He's been milking a dead horse too long",
    "We don't want to put all our eggs in one beach head",
    "It took me aback",
    "For all intensive purposes",
    "Don't know if he can pass the mustard",
    "The ball is in your camp",
    "Stepping up to the plate and understanding both sides of the coin",
    "In my previous experience",
    "We've had a few bumps and grinds along the way",
    "Over the hump and out the door, with high quality",
    "Let's seize the day and make this quarter",
    "Robbing Peter to pay Mary...or whatever",
    "You've got the other end of the aquarium",
    "He would have done it without blinking twice",
    "In like flint",
    "burning the candle at both ends of the stick",
    "Hammered it home until he was blue in the face",
    "Maybe there is a rhyme to the madness",
    "Working the midnight oil",
    "He wants to run the roost",
    "I was living toenail to shoelace",
    "We changed that situation by 360 degrees",
    "They lost a lot of sleepless nights over it",
    "Dumb as nails",
    "We need some hands and legs on the project",
    "He's the preferred son",
    "They got second shrift",
    "We'll be in deep straits",
    "The raw end of the stick",
    "We're behind the gun",
    "I do not know any details. I am just recanting what I was told",
    "He was full of vim and vinegar",
    "I fell off the bandwagon",
    "Do you have any dog faux pas? (intending phobias)",
    "She was out like a rock",
    "She has to tow a fine line",
    "I don't want to rebuild the wheel",
    "The project has had some dips and valleys",
    "The light bulb hit me in the head",
    "We've got to spread our feet and use our hook",
    "I got a basket in one",
    "They are old stogies",
    "That's no skin off my teeth",
    "The tables were reversed",
    "Head and heals above the rest",
    "We just brushed the surface",
    "It's like pulling blood from a stone",
    "He bought the pooch",
    "We're ahead of the ball",
    "We're already milking that cash cow and	now we need to throw all our eggs at it",
    "We need more hands and legs to do the work",
    "Middle of the pack",
    "Falling apart like dominoes",
    "I'm raising havoc",
    "Stick to the letter of my guns",
    "Dredging the barrell",
    "They are in the rock ages",
    "We've got to hone up",
    "I don't want to walk on your toes",
    "We're churning our wheels",
    "That'll be the final nail in all of that hot air",
    "We've got a shoe in the door",
    "It can be doved off",
    "We're going to dine and wine him",
    "That's going to clog it down",
    "Cutting and dicing",
    "Unveil the curtain",
    "Stay with the standard quo",
    "Our ducks are in order",
    "Recreating the wheel",
    "The ball is rolling.  Now we have to get out in front of it",
    "That's the third straw",
    "I'm caught between a hard and a rock",
    "You come out smelling like a grape",
    "He throws a monkey in the wrench",
    "Back stabbed himself in the foot",
    "He's stepping up to the bat",
    "Hot as a pancake",
    "Looking forward to the end of the light	",
    "They've been good campers",
    "I don't want it to fall on flat ears",
    "That was a real kick in the face",
    "It hit me between the heads",
    "We're under the thumb",
    "I can hear the handwriting on the wall",
    "Waiting with belated breath",
    "I'd like to be a fly in the ointment at that meeting",
    "It's a mute point anyway",
    "I can't phantom that",
    "He got raked through the coals",
    "I don't mean to give you gruff",
    "It's the shortest line between two stones",
    "It takes two to tangle",
    "You put the nail on the hammer",
    "It bottles the mind",
    "That's water over the bridge",
    "We have bigger fish to kill",
    "You made a deal and now I'm wreaking the shit from it",
    "That will open up a whole bunch of worms",
    "Weird things keep crapping up",
    "It's too good an offer to pass down",
    "All bets are go",
    "He needs to pick up the ball and roll with it",
    "Feeling below the weather",
    "Stay with it until the dire end	",
    "The numbers were skewered",
    "You get extra browning points",
    "Tied at the hip",
    "A bald face lie",
    "These topics interlap",
    "Dyed in the world businessman",
    "This has come down from the powers to be",
    "We should hold pat",
    "All the glory details",
    "Looking a trojan horse in the mouth",
    "He is being a cheap scape",
    "We'll jump from that bridge when we get to it",
    "Beat a bad dog into a beautiful horse",
    "Cut from the same pie",
    "Half baked crock of soup",
    "Lets not get worked out of shape",
    "Slower than sliced bread",
    "Thats the camel breaking the straw",
    "They were worried stiff",
    "We're walking through egg shells",
    "We need to keep our hands on top of this",
    "The wheel of karma is slapping me in the face",
    "They don't have 2 pennies to piss in",
    "I want to plant a seed to get some wheels spinning",
    "Keep your ears posted",
    "Keep our foot in the game",
    "I've got some forks in the iron",
    "I am internally greatful",
    "Snuffing the candle at both ends",
    "He's quick on his wits",
    "Vulcan mind warp",
    "I've greased the skins",
    "He's on the other end of the fence",
    "They want to get in front of the ball",
    "Tongue in hand",
    "Its time to put our chips on the floor",
    "If the tables were reversed",
    "They're up in their Eiffel towers",
    "Nuts to soup",
    "I can't think of it off the top of my hat",
    "Don't put all your hamsters in one basket",
    "That's a horse of a different species",
    "Tell it to the bailiff",
    "That's no skin off our back",
    "He got off dirt-free",
    "Sitting in my craw",
    "Biting at the bit",
    "slipped in like a glove",
    "Too many hands in the pie",
    "Let's not delve on that",
    "She's the apple of my heart",
    "Slicker than sliced bread",
    "I couldn't get a word in lengthwise",
    "You're going to be back at ground one",
    "She's a tough cookie to crack",
    "Burn the midnight candle",
    "Growing like hotcakes",
    "It makes my blood crawl",
    "We are moving at warpneck speed",
    "This will be our golden cow",
    "We don't want this to be a plane wreck",
    "I coined the market",
    "A tough nut to swallow",
    "Trial by error",
    "We're not sure we need the machines yet, so ordering them now would be immature.",
    "Slowly but slowly",
    "You can't pull the wool over my ears",
    "That's like letting the chicken guard the hen house",
    "He got off dirt-free",
    "We need to get someone with the right skills so we can put our foot through the door",
    "That's the next step to that song",
    "That's right up your bag",
    "That opens up a whole bunch of worms",
    "A monkey in the wrench",
    "A cog in the wheel that won't turn",
    "That's a cul-de-sac off the beaten path",
    "We're breathing down their throats",
    "Don't pull the gun too early",
    "Too many cooks in the broth",
    "I may be smoking, but....",
    "The people go full bored with it .. ",
    "Jack of all traits",
    "Foot through the door",
    "The game is up",
    "Don't want to bite ourselves in the foot",
    "Chewing at the bits",
    "Running around with they're heads chopped off",
    "He can walk circles around him",
    "The only voice in my court",
    "He's buying his time",
    "Take your hands off for...",
    "Now we're picking bones and eggs",
    "Heads & shoulders above",
    "We can't kill our golden eggs",
    "Those things can give us some foot in the doors",
    "I'm going to put my nose to the grinder",
    "Lots of cooks in the broth",
    "The straw that got her ass fired",
    "You hit something right on the nail ",
    "Im just putting a stake in my tent",
    "Fishing for straws",
    "Low lying fruit",
    "Barrel of worms",
    "Early fish catches the worm",
    "I was shitting bullets",
    "The decision was made half-hazardly",
    "Close the stage coach (intending circle the wagons)",
    "I have a pit in my stomach",
    "Piss off and die",
    "They've got the shit by the balls",
    "Casting a wider net than we can swallow",
    "Lets put his foot in the fire",
    "We need to actionize the plan",
    "Stupid as rocks",
    "We'll do the armwork for you",
    "Skip to the chase",
    "Put the heavy arm on them",
    "Leaving you hangin dry",
    "We may be able to play that coin",
    "Taking of like hotcakes",
    "Those guys turned their nose down at the opportunity",
    "Turned their eyebrows up at it",
    "He's winging it from the hip",
    "Keep our foot in the ball game",
    "whats coming down the pike",
    "He's caught between a house and a parking lot",
    "I'm at your beckon call",
    "He has a photogenic memory",
    "He thinks he's the next coming",
    "Those are far and few between",
    "You're singing to the choir",
    "Faster than the sound of light...",
    "That makes my skin curl",
    "From point A to point Z",
    "I know this place like the back of my head",
    "They've got it down to an art",
    "Can't see the forest from the trees",
    "Handing the keys to the fox",
    "They need to get their game together",
    "Lets circle the wagons and develop a game plan",
    "He should count his lucky stars",
    "They've got a foothold in the door",
    "Pushing string uphill",
    "Shake the bushes",
    "Skating uphill in the mud",
    "They are shuffling the deck chairs",
    "If you read between the tea leaves",
    "He doesn't hold a candlestick to them",
    "That's been a bane in our side",
    "We're putting the cart before the egg.",
    "Don't disrupt the apple cart",
    "You're putting the horse before the buggy"
  ];
  const lcSearch = (search || '').toLowerCase();
  return halaprops.filter(h => search ? h.toLowerCase().includes(lcSearch) : true)
}
